name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [ci] # Run after CI completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        # run: pnpm install --frozen-lockfile
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to Vercel
        run: npx vercel --prod
        # env:
        #   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        #   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        #   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
